package callcenter;

import java.util.Date;
import javax.swing.ImageIcon;
import Clases.Reloj;
import Clases.Variables;
import javax.swing.JOptionPane;
import com.sun.awt.AWTUtilities; 
import java.awt.Color;
import java.awt.Shape; 
import java.awt.geom.RoundRectangle2D; 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mariana Valencia
 */
public final class ServerMain extends javax.swing.JFrame {
    
    public boolean touch,touch1,touch2,touch3;
    /**
     * Creates new form ServerMain
     */
    public ServerMain() {
        initComponents();
//        setUndecorated(true);
        setLocationRelativeTo(null);
        fecha_hora();
        usuario(SuperUsuario.Variables_globales.getSession_tipo(),SuperUsuario.Variables_globales.getSesion_usuario());
    }
    public void fecha_hora()
    {
        Date dia = new Date();
        fecha.setText(Integer.toString(dia.getDate()) + "/" + Integer.toString(dia.getMonth() + 1) + "/" + Integer.toString(dia.getYear() + 1900));
        Variables.setHora_reporte(Integer.toString(dia.getDate()) + "-" + Integer.toString(dia.getMonth() + 1) + "-" + Integer.toString(dia.getYear() + 1900));
        Reloj r = new Reloj(hora);
        hora.setOpaque(true);
        hora.setBackground(Color.black);
    }
    
    public void usuario(int tipo, String usuario){
        if(tipo==0){
            Pestana1.setEnabled(false);
        }
        Usuario.setText("Usuario: "+usuario);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBotones = new javax.swing.JDesktopPane();
        close = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        Pestana1 = new javax.swing.JLabel();
        Pestana2 = new javax.swing.JLabel();
        Pestana3 = new javax.swing.JLabel();
        Pestana4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBotones.setMaximumSize(new java.awt.Dimension(820, 400));
        PanelBotones.setMinimumSize(new java.awt.Dimension(820, 400));
        PanelBotones.setOpaque(false);
        getContentPane().add(PanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 820, 400));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/x2.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 60, 60));

        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/6.png"))); // NOI18N
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        logout.setFocusable(false);
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logout.setMinimumSize(new java.awt.Dimension(10, 60));
        logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 20, 10, 60));

        Pestana1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/P1.png"))); // NOI18N
        Pestana1.setToolTipText("");
        Pestana1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pestana1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pestana1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pestana1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pestana1MouseExited(evt);
            }
        });
        getContentPane().add(Pestana1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 50));

        Pestana2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/P2.png"))); // NOI18N
        Pestana2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pestana2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pestana2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pestana2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pestana2MouseExited(evt);
            }
        });
        getContentPane().add(Pestana2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 160, -1));

        Pestana3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/P3.png"))); // NOI18N
        Pestana3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pestana3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pestana3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pestana3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pestana3MouseExited(evt);
            }
        });
        getContentPane().add(Pestana3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 160, -1));

        Pestana4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/P5.png"))); // NOI18N
        Pestana4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pestana4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pestana4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pestana4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Pestana4MouseExited(evt);
            }
        });
        getContentPane().add(Pestana4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 160, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logito.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        hora.setBackground(new java.awt.Color(0, 0, 0));
        hora.setFont(new java.awt.Font("SF Digital Readout", 1, 36)); // NOI18N
        hora.setForeground(new java.awt.Color(255, 0, 0));
        hora.setText("\"\"");
        hora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 130, 30));

        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("\"\"");
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 140, 30));

        Usuario.setFont(new java.awt.Font("Microsoft Tai Le", 0, 24)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Usuario: ");
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 220, 30));
        Usuario.getAccessibleContext().setAccessibleName("Usuario");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo1v2.jpg"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(832, 520));
        jLabel1.setMinimumSize(new java.awt.Dimension(832, 520));
        jLabel1.setPreferredSize(new java.awt.Dimension(832, 520));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pestana1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pestana1MouseEntered
        Pestana1.setIcon(new ImageIcon(getClass().getResource("/recursos/pestaña1.png")));
    }//GEN-LAST:event_Pestana1MouseEntered

    private void Pestana1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pestana1MouseExited
        if(!touch){
            Pestana1.setIcon(new ImageIcon(getClass().getResource("/recursos/P1.png")));
        }
    }//GEN-LAST:event_Pestana1MouseExited

    private void Pestana2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pestana2MouseEntered
        Pestana2.setIcon(new ImageIcon(getClass().getResource("/recursos/pestaña2.png")));
    }//GEN-LAST:event_Pestana2MouseEntered

    private void Pestana2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pestana2MouseExited
        if(!touch1){
            Pestana2.setIcon(new ImageIcon(getClass().getResource("/recursos/P2.png")));
        }
    }//GEN-LAST:event_Pestana2MouseExited

    private void Pestana3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pestana3MouseEntered
        Pestana3.setIcon(new ImageIcon(getClass().getResource("/recursos/pestaña3.png")));
    }//GEN-LAST:event_Pestana3MouseEntered

    private void Pestana3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pestana3MouseExited
        if(!touch2){
            Pestana3.setIcon(new ImageIcon(getClass().getResource("/recursos/P3.png")));
        }
    }//GEN-LAST:event_Pestana3MouseExited

    private void Pestana4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pestana4MouseEntered
        Pestana4.setIcon(new ImageIcon(getClass().getResource("/recursos/pestaña5.png")));
    }//GEN-LAST:event_Pestana4MouseEntered

    private void Pestana4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pestana4MouseExited
        if(!touch3){
            Pestana4.setIcon(new ImageIcon(getClass().getResource("/recursos/P5.png")));
        }
    }//GEN-LAST:event_Pestana4MouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setIcon(new ImageIcon(getClass().getResource("/recursos/x1.png")));
        if(logout.getX()==759&&logout.getWidth()==10){
            new Thread(new hilo_cerrarsesion(logout, true)).start();
        }
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setIcon(new ImageIcon(getClass().getResource("/recursos/x2.png")));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setIcon(new ImageIcon(getClass().getResource("/recursos/5.png")));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setIcon(new ImageIcon(getClass().getResource("/recursos/6.png")));
    }//GEN-LAST:event_logoutMouseExited

    private void Pestana1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pestana1MouseClicked
        if (Pestana1.isEnabled()) {
            Pestana1.setIcon(new ImageIcon(getClass().getResource("/recursos/pestaña1.png")));
            touch = true;
            Pestana2.setIcon(new ImageIcon(getClass().getResource("/recursos/P2.png")));
            touch1 = false;
            Pestana3.setIcon(new ImageIcon(getClass().getResource("/recursos/P3.png")));
            touch2 = false;
            Pestana4.setIcon(new ImageIcon(getClass().getResource("/recursos/P5.png")));
            touch3 = false;
            Panel1 p1 = new Panel1();
            PanelBotones.removeAll();
            PanelBotones.add(p1);
            p1.setVisible(true);
        }
    }//GEN-LAST:event_Pestana1MouseClicked

    private void Pestana2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pestana2MouseClicked
        Pestana1.setIcon(new ImageIcon(getClass().getResource("/recursos/P1.png")));
        touch = false;
        Pestana2.setIcon(new ImageIcon(getClass().getResource("/recursos/pestaña2.png")));
        touch1 = true;
        Pestana3.setIcon(new ImageIcon(getClass().getResource("/recursos/P3.png")));
        touch2 = false;
        Pestana4.setIcon(new ImageIcon(getClass().getResource("/recursos/P5.png")));
        touch3 = false;
        Panel2 p2 = new Panel2();
        PanelBotones.removeAll();
        PanelBotones.add(p2);
        p2.setVisible(true);
    }//GEN-LAST:event_Pestana2MouseClicked

    private void Pestana3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pestana3MouseClicked
        Pestana1.setIcon(new ImageIcon(getClass().getResource("/recursos/P1.png")));
        touch = false;
        Pestana2.setIcon(new ImageIcon(getClass().getResource("/recursos/P2.png")));
        touch1 = false;
        Pestana3.setIcon(new ImageIcon(getClass().getResource("/recursos/pestaña3.png")));
        touch2 = true;
        Pestana4.setIcon(new ImageIcon(getClass().getResource("/recursos/P5.png")));
        touch3 = false;
        Panel3 p3 = new Panel3();
        PanelBotones.removeAll();
        PanelBotones.add(p3);
        p3.setVisible(true);
    }//GEN-LAST:event_Pestana3MouseClicked

    private void Pestana4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pestana4MouseClicked
        Pestana1.setIcon(new ImageIcon(getClass().getResource("/recursos/P1.png")));
        touch = false;
        Pestana2.setIcon(new ImageIcon(getClass().getResource("/recursos/P2.png")));
        touch1 = false;
        Pestana3.setIcon(new ImageIcon(getClass().getResource("/recursos/P3.png")));
        touch2 = false;
        Pestana4.setIcon(new ImageIcon(getClass().getResource("/recursos/pestaña5.png")));
        touch3 = true;
        Panel4 p4 = new Panel4();
        PanelBotones.removeAll();
        PanelBotones.add(p4);
        p4.setVisible(true);
    }//GEN-LAST:event_Pestana4MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Supervisor.Login h = new Supervisor.Login();
        h.setLocationRelativeTo(null);
        SuperUsuario.Variables_globales.setSesion(false);
        SuperUsuario.Variables_globales.setSesion_usuario("");
        SuperUsuario.Variables_globales.setSession_tipo(0);
        this.dispose();
        h.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 100, 100);
        AWTUtilities.setWindowShape(this, forma);
    }//GEN-LAST:event_formComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ServerMain().setVisible(true);
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PanelBotones;
    private javax.swing.JLabel Pestana1;
    private javax.swing.JLabel Pestana2;
    private javax.swing.JLabel Pestana3;
    private javax.swing.JLabel Pestana4;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel close;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel logout;
    // End of variables declaration//GEN-END:variables
}
